# Generated by Django 2.2.4 on 2020-02-03 05:57

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('table', models.TextField(blank=True, null=True)),
                ('cik', models.IntegerField(db_index=True)),
                ('primarysymbol', models.CharField(db_index=True, max_length=200)),
                ('markettier', models.CharField(blank=True, max_length=200, null=True)),
                ('sicdescription', models.CharField(blank=True, max_length=1000, null=True)),
                ('jsonnn', jsonfield.fields.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('companyname', 'cik', 'primarysymbol'),
            },
        ),
    ]
