# Generated by Django 2.2.4 on 2020-02-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EaganJones', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='entityid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='companies',
            name='marketoperator',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='companies',
            name='primaryexchange',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='companies',
            name='siccode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='companies',
            name='sicdescription',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
